
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Dashboard</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <div class="row">
                <div class="col-lg-3 col-md-6" id="dashboard-members">
                    
                
                </div>
            
                <div class="col-lg-3 col-md-6" id="dashboard-services">
                    
                </div>
            
            
                <div class="col-lg-3 col-md-6" id="dashboard-users">
                    
                </div>
            
            
                <div class="col-lg-3 col-md-6" id="dashboard-clients">
                    
                </div>
            </div>

<script>
<?php $this->inlineScript()->captureStart();?>
    
                $.ajax({
                    
                    url: '<?php echo $this->url(array('controller' => 'admin_members', 'action' => 'dashboard'), 'default', true);?>',
                    cache: false
                    
                }).done (function (data) {
                        
                        var element = $('#dashboard-members');
                        
                        element.append(data);
                    
                    
                }).fail (function () {
                    alert('Unable to load members');
                }).always(function () {
                    
                });
                
                $.ajax({
                    
                    url: '<?php echo $this->url(array('controller' => 'admin_services', 'action' => 'dashboard'), 'default', true);?>',
                    cache: false
                    
                }).done (function (data) {
                        
                        var element = $('#dashboard-services');
                        
                        element.append(data);
                    
                    
                }).fail (function () {
                    alert('Unable to load services');
                }).always(function () {
                    
                });
                
                $.ajax({
                    
                    url: '<?php echo $this->url(array('controller' => 'admin_users', 'action' => 'dashboard'), 'default', true);?>',
                    cache: false
                    
                }).done (function (data) {
                        
                        var element = $('#dashboard-users');
                        
                        element.append(data);
                    
                    
                }).fail (function () {
                    alert('Unable to load users');
                }).always(function () {
                    
                });
                
                $.ajax({
                    
                    url: '<?php echo $this->url(array('controller' => 'admin_clients', 'action' => 'dashboard'), 'default', true);?>',
                    cache: false
                    
                }).done (function (data) {
                        
                        var element = $('#dashboard-clients');
                        
                        element.append(data);
                    
                    
                }).fail (function () {
                    alert('Unable to load clients');
                }).always(function () {
                    
                });
                
<?php $this->inlineScript()->captureEnd();?>
</script>